#!/usr/bin/env bash
# Regenerate .gitignore.
#
# The pack-owned part is derived from the current pack zip rather than typed by
# hand, so a future pack that ships a new top-level folder is covered without
# anyone remembering to edit this. update.sh calls this after every update.
set -euo pipefail
ROOT=$(cd "$(dirname "$0")" && pwd)
cd "$ROOT"

PACK=$(ls -1 packs/*.zip 2>/dev/null | sort -V | tail -1 || true)

{
	cat <<'EOF'
# Generated by gen-ignore.sh. Edit that, not this.

# Server pack zips: hundreds of MB, re-downloadable from the TFG releases page.
packs/*.zip
# Pre-update snapshots of world/player data. Local safety net, not source.
backups/

# Secrets that may end up in overrides/ (Discord tokens, rcon passwords, ...).
overrides/**/*secret*
overrides/**/*token*
overrides/**/*.key
overrides/**/*.pem
EOF

	if [[ -n $PACK ]]; then
		printf '\n# Pack-owned top-level entries, from %s.\n' "$(basename "$PACK")"
		printf '# Listed so a stray copy of the pack unpacked in here cannot be\n'
		printf '# committed. overrides/ is exempt: holding such files is its job.\n'
		# Files this repo owns at its own root. Without this, the pack's
		# README.md would make us ignore our own documentation. Not read from
		# git ls-files: that is empty before the first commit.
		OURS='README.md'
		unzip -Z1 "$PACK" | sed 's#/.*##' | sort -u | while read -r n; do
			[[ -n $n ]] || continue
			grep -qxF "$n" <<<"$OURS" && continue
			printf '/%s\n' "$n"
		done
	fi
} > .gitignore

echo "Wrote .gitignore${PACK:+ (pack: $(basename "$PACK"))}"
